version: "3.9"

name: filmes-app
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: filmes-backend
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
    healthcheck:
      test: ["CMD-SHELL", "node -e 'require(\"net\").createConnection(8080, \"localhost\").on(\"connect\",()=>process.exit(0)).on(\"error\",()=>process.exit(1))'"]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: filmes-frontend
    environment:
      # o front precisa falar com o backend pelo host do container
      VITE_API_URL: http://backend:8080/api
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
