services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: projeto-filmes-backend
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: projeto-filmes-frontend
    environment:
      VITE_API_URL: http://localhost:8080/api
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
