services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: projeto-filmes-backend
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
    networks: [appnet]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: projeto-filmes-frontend
    environment:
      VITE_API_URL: http://127.0.0.1:8080/api
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    depends_on: [backend]
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --strictPort
    networks: [appnet]

networks:
  appnet:
    driver: bridge
