script: |
        cd /opt/filmes

        cat <<EOF > docker-compose.prod.yml
        version: '3.8'

        services:
          backend:
            image: ${{ secrets.DOCK-ERHUB_USERNAME }}/projeto-filmes-backend:latest
            restart: always
            env_file:
              - backend.env
            networks:
              - app-network

          frontend:
            image: ${{ secrets.DOCKERHUB_USERNAME }}/projeto-filmes-frontend:latest
            restart: always
            ports:
              - "80:80"
              - "443:443"
            volumes:
              - /etc/letsencrypt:/etc/letsencrypt:ro
            depends_on:
              - backend
            networks:
              - app-network

        networks:
          app-network:
            driver: bridge
        EOF

        docker compose -f docker-compose.prod.yml pull
        docker compose -f docker-compose.prod.yml up -d